#!/bin/sh
### BEGIN INIT INFO
# Provides:          Fax Observer
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fax Observer
# Description:       
### END INIT INFO
 
export USER='pi'
 
eval cd ~$USER
 
# Check state
case "$1" in
  start)
    su $USER -c 'sh incomingfaxobserver.sh /home/pi/firemergency/mail_input /home/pi/firemergency/firEmergency1.9.9.33-Linux/files/fax/input/'
    echo "Starting incomingfaxobserver for $USER"
  ;;
  stop)
    pkill incomingfaxobserver
    echo "incomingfaxobserver stopped"
  ;;
  *)
    echo "Usage: {start|stop}"
    exit 1
  ;;
esac
 
exit 0
