#!/bin/sh
### BEGIN INIT INFO
# Provides:          Incoming fax observer
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Observes an given directory
# Description:       In case of new fax (pdf): convert it to tif and run ocr
### END INIT INFO

export USER='pi'
 
eval cd ~$USER

SCRIPT="/home/pi/firemergency/"
SCRIPTNAME="incomingfaxobserver.sh"
INPUT="/media/fritzbox"
OUTPUT="/home/pi/firemergency/"
TXT="/home/pi/firemergency/txt/"

# Actions
case "$1" in
    start)
        # START
        sh $SCRIPT$SCRIPTNAME $INPUT $OUTPUT $TXT
        ;;
    stop)
        # STOP
        killall incomingfaxobserver.sh
        ;;
    restart)
        # RESTART
        killall incomingfaxobserver.sh
        sh $SCRIPT$SCRIPTNAME $INPUT $OUTPUT $TXT
        ;;
esac
 
exit 0
