#!/bin/sh
### BEGIN INIT INFO
# Provides:          Mailbox Observer
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mailbox Observer
# Description:       
### END INIT INFO
 
export USER='pi'
 
eval cd ~$USER
 
# Check state
case "$1" in
  start)
    su $USER -c 'node /home/pi/firemergency/firEmergencyOnRPi/mailboxobserver.js'
    echo "Starting Mailbox Observer for $USER"
  ;;
  stop)
    pkill mailboxobserver
    echo "Mailbox Observer stopped"
  ;;
  *)
    echo "Usage: {start|stop}"
    exit 1
  ;;
esac
 
exit 0
